language: groovy
install: ./gradlew assemble -x signArchives
script: ./gradlew check -x signArchives
jdk:
  - oraclejdk7
  - oraclejdk8
git:
  submodules: false
env:
   global:
   - _JAVA_OPTIONS='-Xverify:none'
